title: Resume Samples
description: Sample Resume
author: Sample Resume
github: http://findyourmover.us
about: Resume Samples, Curriculum Vitae Samples.
disqus_shortname: wisnu
google_analytics: UA-111747717-4
avatar_url: /static/img/resume.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/summonagus"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/agusmakmun"

share:
  twitter_username: lowongankerja
  fb_appid: 1749788565247320

urls:
    - text: XML Feed
      url: /sitemap.xml

url: "https://donesiaha.github.io"
baseurl: ""
paginate: 100
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['production']
