-
    slug: environmental-graphic-design-signage-sistems-interior-wayfinding-senaletica-para-empresas-diseno-de-locales
    name: 'Environmental Graphic Design, Signage Sistems, Interior wayfinding, señaletica para empresas, diseño de locales comerciales Canton Crossing - Ashton Design'
    image: 'https://i.pinimg.com/originals/1b/93/b0/1b93b0a1711c2e8d49d6c6565b9de82b.jpg'
    url: /project/environmental-graphic-design-signage-sistems-interior-wayfinding-senaletica-para-empresas-diseno-de-locales/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: graphic-design-trends-2018-magdiel-is-an-artistcreative-director-born-in-cuba-living-in-dallas
    name: 'Graphic design trends 2018 Magdiel is an artist/creative director born in Cuba, living in Dallas, Texas. Through his 12+ year career, Magdiel has worked on, and lead, projects ranging from brand identity to conceptual art and environmental design. He'
    image: 'https://i.pinimg.com/originals/40/b5/a7/40b5a77121a11a3ee5364c223296c5fe.jpg'
    url: /project/graphic-design-trends-2018-magdiel-is-an-artistcreative-director-born-in-cuba-living-in-dallas/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: wayfinding-system-for-primary-school-on-behance
    name: 'Wayfinding System for primary school on Behance'
    image: 'https://i.pinimg.com/originals/fe/62/26/fe622695b80bda7fc3163eb84abe699d.jpg'
    url: /project/wayfinding-system-for-primary-school-on-behance/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: i-enjoy-this-photo-because-it-shows-how-the-real-world-really-is-not-everything
    name: 'I enjoy this photo because it shows how the real world really is. Not everything is straight and in order out in the actual world, so why should it be in a photographer''s studio?'
    image: 'https://i.pinimg.com/originals/d1/b1/4a/d1b14a5669ecea05786267684526154d.jpg'
    url: /project/i-enjoy-this-photo-because-it-shows-how-the-real-world-really-is-not-everything/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: troika-allestimenti-grafica-istallazioni-design-totem
    name: 'Troika allestimenti grafica istallazioni design totem'
    image: 'https://i.pinimg.com/originals/14/23/11/142311b8e4956c974c1ddc2218037fc5.jpg'
    url: /project/troika-allestimenti-grafica-istallazioni-design-totem/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: the-best-in-outdoor-creativity-ibm-wins-grand-prix-at-cannes
    name: 'The Best In Outdoor Creativity: IBM Wins Grand Prix At Cannes'
    image: 'https://i.pinimg.com/originals/c0/81/bb/c081bb77dfb4c82555056e6723716155.jpg'
    url: /project/the-best-in-outdoor-creativity-ibm-wins-grand-prix-at-cannes/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: awesome-signage-design
    name: 'Awesome Signage Design'
    image: 'https://i.pinimg.com/originals/df/5e/c3/df5ec384887bf2e6773094d910645c5a.jpg'
    url: /project/awesome-signage-design/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: ichi-sushi
    name: 'ICHI Sushi'
    image: 'https://i.pinimg.com/originals/01/6c/bf/016cbf16367e003e5975647b45a03153.jpg'
    url: /project/ichi-sushi/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: goodhood-goodhood-creative
    name: 'Goodhood (Goodhood Creative)'
    image: 'https://i.pinimg.com/originals/20/69/bb/2069bb280651a86d97a662c5601bf2ac.jpg'
    url: /project/goodhood-goodhood-creative/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: northern-territory
    name: 'Northern Territory'
    image: 'https://i.pinimg.com/originals/a1/5b/af/a15baf1d068829be2a3a3a31842b2cea.jpg'
    url: /project/northern-territory/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: hume-global-learning-centre-library-identity-system-and-signage-design-by-pidgeon
    name: 'Hume Global Learning Centre & Library identity system and signage | Design by Pidgeon'
    image: 'https://i.pinimg.com/originals/f2/ba/a8/f2baa842c9bf25b5895513f7e34b6d39.jpg'
    url: /project/hume-global-learning-centre-library-identity-system-and-signage-design-by-pidgeon/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: beacon-park-is-the-second-of-several-communities-developed-by-great-park-neighborhoods-sited-around
    name: 'Beacon Park is the second of several communities developed by Great Park Neighborhoods, sited around the perimeter of the Orange County Great Park...'
    image: 'https://i.pinimg.com/originals/ec/e3/4a/ece34a8ec7b71c95bf16b206b8dd71f2.jpg'
    url: /project/beacon-park-is-the-second-of-several-communities-developed-by-great-park-neighborhoods-sited-around/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: on-the-creative-market-blog-artist-uses-typography-and-shadows-to-create-stunning-sundial
    name: 'On the Creative Market Blog - Artist Uses Typography and Shadows to Create Stunning Sundial Mural'
    image: 'https://i.pinimg.com/originals/8d/cb/dc/8dcbdc558330d85a156c3c40a932f98f.jpg'
    url: /project/on-the-creative-market-blog-artist-uses-typography-and-shadows-to-create-stunning-sundial/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: directory-visual-communication-graphic-design-information-design-color-system-wayfinding-environmental-signage
    name: 'Directory | visual communication. graphic design. information design. color system. wayfinding. environmental. signage.'
    image: 'https://i.pinimg.com/originals/97/86/e1/9786e1ddbf21709c4770e2233b84a2e7.jpg'
    url: /project/directory-visual-communication-graphic-design-information-design-color-system-wayfinding-environmental-signage/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: parking-signage-project-environmental-graphic-design-signage-sistems-interior-wayfinding-senaletica-para-empresas-disen
    name: 'Parking signage project  Environmental Graphic Design, Signage Sistems, Interior wayfinding, señaletica para empresas, diseño de locales comerciales Canton Crossing | #Wayfinding | #Signage'
    image: 'https://i.pinimg.com/originals/a6/10/07/a6100763bd139d916a613e7e4d93045e.jpg'
    url: /project/parking-signage-project-environmental-graphic-design-signage-sistems-interior-wayfinding-senaletica-para-empresas-disen/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: if-we-wanted-something-with-more-impact-but-less-malleable
    name: '// if we wanted something with more impact but less malleable'
    image: 'https://i.pinimg.com/originals/b5/e4/3d/b5e43d2bff8e40c3fd40d5db9b6fdd77.png'
    url: /project/if-we-wanted-something-with-more-impact-but-less-malleable/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: culture-graphic-designers-portfolio-work-i-like-how-she-takes-classic-art-signage-and-makes
    name: 'Culture: graphic designer''s portfolio work. I like how she takes classic art/ signage and makes it distorted. It''s a mix of old and new'
    image: 'https://i.pinimg.com/originals/86/13/2c/86132c02f1d382405cef5bf83a59cc76.jpg'
    url: /project/culture-graphic-designers-portfolio-work-i-like-how-she-takes-classic-art-signage-and-makes/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: graphic-design-worlds-january-2011-experimental-jetset
    name: 'Graphic Design Worlds  January 2011 - Experimental Jetset'
    image: 'https://i.pinimg.com/originals/c8/01/e2/c801e2b2197d3d60aca0f22c53df30fb.jpg'
    url: /project/graphic-design-worlds-january-2011-experimental-jetset/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: nato-summit-lisbon-by-p-06-atelier-via-behance
    name: 'NATO SUMMIT LISBON by P-06 atelier , via Behance'
    image: 'https://i.pinimg.com/originals/c1/7e/c8/c17ec81d8051fcf38b4165a41ea2cf45.jpg'
    url: /project/nato-summit-lisbon-by-p-06-atelier-via-behance/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: wall-graphics-office-design-google-search
    name: 'wall graphics office design - Google Search'
    image: 'https://i.pinimg.com/originals/85/40/ee/8540ee6833da965274bb39792bac40af.jpg'
    url: /project/wall-graphics-office-design-google-search/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: the-vibrant-colourful-murals-of-lakwena-macliver-at-cdwfestival-cdw16-typography-art-via-at-mhd-studio
    name: 'The Vibrant & Colourful murals of Lakwena Macliver  @CDWfestival #cdw16 #typography #art  via @MHD_Studio'
    image: 'https://i.pinimg.com/originals/9f/52/07/9f52073eb4361b08b1dce7381d2346bc.jpg'
    url: /project/the-vibrant-colourful-murals-of-lakwena-macliver-at-cdwfestival-cdw16-typography-art-via-at-mhd-studio/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: carnegie-museum-of-art-pittsburgh-54th-carnegie-international-2003
    name: 'Carnegie Museum of Art, Pittsburgh – 54th Carnegie International 2003'
    image: 'https://i.pinimg.com/originals/f4/b7/aa/f4b7aae36c19d35e2a5be1051cf9acef.jpg'
    url: /project/carnegie-museum-of-art-pittsburgh-54th-carnegie-international-2003/
    date: 'Apr 2017'
    tags: [resume]
-
    slug: 6th-street-mural
    name: '6th Street Mural'
    image: 'https://i.pinimg.com/originals/ae/0c/cd/ae0ccdf9431881e03ad46852fc80f0bb.jpg'
    url: /project/6th-street-mural/
    date: 'Apr 2017'
    tags: [resume]
